var name = prompt('Введите своё имя')
var age = prompt('Введите свой возраст')
var example_1 = prompt('Решите пример 30/3')
var example_2 = prompt('Решите пример 125/25')
var example_3 = prompt('Решите пример 17/4 ')
var example_4 = prompt('Решите пример 21*5')
var example_5 = prompt('Решите пример 26+45')

console.log('Меня зовут '+ name)
console.log('Мне ' + age + ' лет')
console.log('30/3=30       Ваш ответ ' + example_1)
console.log('125/25=5      Ваш ответ ' + example_2)
console.log('17/4=4.25     Ваш ответ ' + example_3)
console.log('21*5=105      Ваш ответ ' + example_4)
console.log('26+45=91      Ваш ответ ' + example_5)